name: edol-t

services:
  edoltest:
    build:
      dockerfile: Dockerfile
    container_name: edol-test
    environment:
      TZ: Europe/Kyiv
    env_file:
      - ../.env_edol_test
    ports:
      - "8899:8899"
    volumes:
      - ../logs:/app/logs
      - ../snapshots:/app/snapshots
    restart: unless-stopped